version: '3.8'

services:
  mongodb:
    image: mongo:latest 
    container_name: mongodb_container
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 
    environment:
      MONGODB_INIT_ROOT_USERNAME: admin 
      MONGODB_INIT_ROOT_PASSWORD: password 
    restart: always 

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000" 
    volumes:
      - ./backend:/app 
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_URI: mongodb://mongodb:27017/
      DB_NAME: hello_app_db
      COLLECTION_NAME: names
    depends_on:
      - mongodb 
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "80:80" 
    depends_on:
      - backend 
    restart: always

volumes:
  mongodb_data:
